do {
  ns ns0 http://www.stibosystems.com/step
  ---
  {
    ns0#"STEP-ProductInformation" @("AllowInvalidValues": "N", "AutoApprove": "N", "AutoFillQualifiers": "N", "AutoInitiate": "N", "ContextID": "Context1", "ExportContext": "Context1", "ExportTime": "2022-06-21 12:31:01", "ExportTransactionID": "-1", "ReplaceAttributeLinks": "N", "ReplaceClassificationToClassificationCrossReferences": "N", "ReplaceClassificationValues": "N", "ReplaceEntityValues": "N", "ReplaceOverrideToSubProductReferences": "N", "ReplaceProductToClassificationReferences": "N", "ReplaceProductToProductCrossReferences": "N", "ReplaceProductValues": "N", "ReplaceTerms": "CLEAR_ONLY_FOR_IMPORTED_PRODUCTS", "ReplaceValidUserTypesForAttributes": "N", "STEPWorkflowImportEvent": "N", "SingleUpdateMode": "N", "StateflowImportEvent": "N", "SuppressReTranslations": "N", "UseContextLocale": "false", "WorkspaceID": "Approved"): do {
      ns ns0 http://www.stibosystems.com/step
      ---
      {
        "Assets" @("RejectNewAssets": "false"): {
          "Asset" @("ID": "IMG_69617", "Referenced": "true", "Republished": "false", "Selected": "false", "UserTypeID": "Web Image"): {
            "KeyValue" @("KeyID": "BBBY_IMG_KEY"): "IMG_69617",
            "Name" @("Changed": "false"): "IMG_69617",
            "ClassificationReference" @("Changed": "false", "ClassificationID": "DigitalMerchandisingImages", "stbEmbed": "false", "stbEmbedded": "false"): null,
            "Values": {
              "Value" @("AttributeID": "IMAGESHOTTYPE", "Changed": "false", "Derived": "false"): "p",
              "Value" @("AttributeID": "IMAGETYPE", "Changed": "false", "Derived": "false"): "High Res",
              "Value" @("AttributeID": "IMAGERESOLUTION", "Changed": "false", "Derived": "false"): "300",
              "Value" @("AttributeID": "CD_CODE", "Changed": "false", "Derived": "false"): "2841",
              "Value" @("AttributeID": "IMAGEORIENTATION", "Changed": "false", "Derived": "false"): "SQUARE",
              "Value" @("AttributeID": "IMAGEFILENAME", "Changed": "false", "Derived": "false"): "6961714844147p.jpg",
              "Value" @("AttributeID": "PHOTOSTUDIONAME", "Changed": "false", "Derived": "false"): "BRENNER PHOTO",
              "Value" @("AttributeID": "ITEMCODE", "Changed": "false", "Derived": "false"): "IMG_69617",
              "Value" @("AttributeID": "IMAGESIZE", "Changed": "false", "Derived": "false"): "2000 X 2000",
              "Value" @("AttributeID": "IMAGEURL", "Changed": "false", "Derived": "false"): "http://s7d1.scene7.com/is/image/BedBathandBeyond/6961714844147p",
              "Value" @("AttributeID": "CDPROVIDEDDATE", "Changed": "false", "Derived": "false"): "2013-04-22",
              "Value" @("AttributeID": "ITEMID", "Changed": "false", "Derived": "false"): "IMG_69617",
              "Value" @("AttributeID": "IMAGESRCTYPE", "Changed": "false", "Derived": "false"): "V"
            }
          }
        },
        ns0#"Products" @("RejectNewProducts": "false"): {
          "Product" @("Changed": "false", "ID": "777410", "ParentID": "EPH_451367", "Referenced": "false", "Republished": "true", "Selected": "true", "UserTypeID": "BeyondSKU"): {
            "KeyValue" @("KeyID": "BBBY_SKU_KEY"): "14844147",
            "Name" @("Changed": "true"): "14844147_BABYSTEP FOOD PREP",
            "ClassificationReference" @("Changed": "true", "ClassificationID": "BINVALUETEXT_55576665", "Type": "LOVValue_BinValue_Reference", "stbEmbed": "false", "stbEmbedded": "false"): null,
            "ClassificationReference" @("Changed": "true", "ClassificationID": "BIN_5012_VALUE_99999", "Type": "LOVValue_BinValue_Reference", "stbEmbed": "false", "stbEmbedded": "false"): null,
            "ClassificationReference" @("Changed": "true", "ClassificationID": "BIN_5035_VALUE_10001", "Type": "LOVValue_BinValue_Reference", "stbEmbed": "false", "stbEmbedded": "false"): null,
            "ClassificationReference" @("Changed": "true", "ClassificationID": "BIN_5074_VALUE_99999", "Type": "LOVValue_BinValue_Reference", "stbEmbed": "false", "stbEmbedded": "false"): null,
            "ClassificationReference" @("Changed": "true", "ClassificationID": "BIN_5082_VALUE_99999", "Type": "LOVValue_BinValue_Reference", "stbEmbed": "false", "stbEmbedded": "false"): null,
            "ClassificationReference" @("Changed": "true", "ClassificationID": "BIN_5083_VALUE_99999", "Type": "LOVValue_BinValue_Reference", "stbEmbed": "false", "stbEmbedded": "false"): null,
            "ClassificationReference" @("Changed": "true", "ClassificationID": "BIN_5084_VALUE_99999", "Type": "LOVValue_BinValue_Reference", "stbEmbed": "false", "stbEmbedded": "false"): null,
            "ClassificationReference" @("Changed": "true", "ClassificationID": "BIN_5085_VALUE_99999", "Type": "LOVValue_BinValue_Reference", "stbEmbed": "false", "stbEmbedded": "false"): null,
            "ClassificationReference" @("Changed": "true", "ClassificationID": "BIN_5219_VALUE_99999", "Type": "LOVValue_BinValue_Reference", "stbEmbed": "false", "stbEmbedded": "false"): null,
            "ClassificationReference" @("Changed": "true", "ClassificationID": "BIN_5265_VALUE_99999", "Type": "LOVValue_BinValue_Reference", "stbEmbed": "false", "stbEmbedded": "false"): null,
            "ClassificationReference" @("Changed": "true", "ClassificationID": "BIN_5283_VALUE_99999", "Type": "LOVValue_BinValue_Reference", "stbEmbed": "false", "stbEmbedded": "false"): null,
            "ClassificationReference" @("Changed": "true", "ClassificationID": "BIN_5284_VALUE_99999", "Type": "LOVValue_BinValue_Reference", "stbEmbed": "false", "stbEmbedded": "false"): null,
            "ClassificationReference" @("Changed": "true", "ClassificationID": "BIN_5286_VALUE_99999", "Type": "LOVValue_BinValue_Reference", "stbEmbed": "false", "stbEmbedded": "false"): null,
            "ClassificationReference" @("Changed": "true", "ClassificationID": "BIN_8000_VALUE_48400", "Type": "LOVValue_BinValue_Reference", "stbEmbed": "false", "stbEmbedded": "false"): null,
            "ClassificationReference" @("Changed": "true", "ClassificationID": "JDA_BEYOND_44078", "Type": "Primary_Vendor", "stbEmbed": "false", "stbEmbedded": "false"): null,
            "ProductCrossReference" @("Changed": "true", "ProductID": "USA_NJ_COO", "Type": "Product_to_COO", "stbEmbed": "false", "stbEmbedded": "false"): {
              "Product" @("Changed": "false", "ID": "USA_NJ_COO", "ParentID": "USA_COO", "Referenced": "false", "Republished": "false", "Selected": "true", "UserTypeID": "COO_State/PR"): {
                "Name" @("Changed": "false"): "USA NEW JERSEY",
                "Values": {
                  "Value" @("AttributeID": "PRCODE", "Changed": "false", "Derived": "false"): "NJ",
                  "Value" @("AttributeID": "CTRYCOD", "Changed": "false", "Derived": "false"): "USA",
                  "Value" @("AttributeID": "PRNAME", "Changed": "false", "Derived": "false"): "NEW JERSEY",
                  "Value" @("AttributeID": "CTRYNAM", "Changed": "false", "Derived": "false"): "UNITED STATES"
                }
              }
            },
            "ProductCrossReference" @("Changed": "true", "ProductID": "LOVVALUE9306212", "Type": "PromotionalAttribute_to_WebProduct", "stbEmbed": "false", "stbEmbedded": "false"): {
              "KeyValue" @("KeyID": "BBBY_LOV_NAME_KEY"): "Baby BPA Free_9_20||PromotionalAttributeValuesLOV",
              "MetaData": {
                "Value" @("AttributeID": "PROMOTIONALSTARTDATE", "Changed": "true", "Derived": "false"): "2012-08-01 00:00:00",
                "Value" @("AttributeID": "PROMOTIONVALIDFORBBBY", "Changed": "true", "Derived": "false", "ID": "1"): "Yes",
                "Value" @("AttributeID": "PROMOTIONVALIDFORCA", "Changed": "true", "Derived": "false", "ID": "3"): "No",
                "Value" @("AttributeID": "PROMOTIONALENDDATE", "Changed": "true", "Derived": "false"): "2013-04-02 00:00:00",
                "Value" @("AttributeID": "PROMOTIONVALIDFORBABY", "Changed": "true", "Derived": "false", "ID": "1"): "Yes"
              },
              "Product" @("Changed": "false", "ID": "LOVVALUE9306212", "ParentID": "PromotionalAttributeValuesLOV", "Referenced": "false", "Republished": "false", "Selected": "true", "UserTypeID": "LOV_Value"): {
                "Name" @("Changed": "false"): "Baby BPA Free_9_20",
                "Values": {
                  "Value" @("AttributeID": "PROMOVALIDFORHARMON", "Changed": "false", "Derived": "false", "ID": "1"): "Yes",
                  "Value" @("AttributeID": "PROMOCODE", "Changed": "false", "Derived": "false"): "9_20",
                  "Value" @("AttributeID": "PROMOVALIDFORCA", "Changed": "false", "Derived": "false", "ID": "3"): "No",
                  "Value" @("AttributeID": "PROMOPLACEHOLDER", "Changed": "false", "Derived": "false"): "PLSR,PDPT,PRINFO",
                  "Value" @("AttributeID": "PROMOVALIDFORBBBY", "Changed": "false", "Derived": "false", "ID": "1"): "Yes",
                  "Value" @("AttributeID": "LOVtoUseID", "Changed": "false", "Derived": "false"): "PromotionalAttributeValuesLOV",
                  "Value" @("AttributeID": "PROMOATTRIBUTEVALUENAMESPECIAL", "Changed": "false", "Derived": "false"): "<lt/>span class=\"prod-attrib prod-attrib-bpa prod-attrib-feo\"<gt/>BPA Free<lt/>/span<gt/>",
                  "Value" @("AttributeID": "LOVDISPLAYNAME", "Changed": "false", "Derived": "false"): "Baby BPA Free",
                  "Value" @("AttributeID": "PROMOATTRIBUTEVALUECODE", "Changed": "false", "Derived": "false"): "20",
                  "Value" @("AttributeID": "LOVName", "Changed": "false", "Derived": "false"): "Baby BPA Free_9_20",
                  "Value" @("AttributeID": "PROMOATTRIBUTEVALUENAME", "Changed": "false", "Derived": "false"): "Baby BPA Free",
                  "Value" @("AttributeID": "STATUS", "Changed": "false", "Derived": "false"): "A",
                  "MultiValue" @("AttributeID": "PROMOINTVALIDSTATUS", "Changed": "false"): {
                    "Value" @("Changed": "false", "Derived": "false", "ID": "1"): "Yes"
                  },
                  "Value" @("AttributeID": "LOVID", "Changed": "false", "Derived": "false"): "9_20",
                  "Value" @("AttributeID": "PROMOVALIDFORBABY", "Changed": "false", "Derived": "false", "ID": "1"): "Yes",
                  "Value" @("AttributeID": "PROMOSEQUENCENUMBER", "Changed": "false", "Derived": "false"): "44",
                  "Value" @("AttributeID": "PROMOATTRIBUTECODE", "Changed": "false", "Derived": "false"): "9"
                }
              }
            },
            "ProductCrossReference" @("Changed": "true", "ProductID": "STYLE-31102953", "Type": "StyleToSKU", "stbEmbed": "false", "stbEmbedded": "false"): {
              "Product" @("Changed": "false", "ID": "STYLE-31102953", "ParentID": "Styles", "Referenced": "false", "Republished": "false", "Selected": "true", "UserTypeID": "Style"): {
                "Name" @("Changed": "false"): "Style-31102953",
                "ClassificationReference" @("Changed": "false", "ClassificationID": "JDA_BEYOND_44078", "Type": "Primary_Vendor", "stbEmbed": "false", "stbEmbedded": "false"): null,
                "ClassificationReference" @("Changed": "false", "ClassificationID": "CLASS_883760190", "Type": "Product_Merchandising_Reference", "stbEmbed": "false", "stbEmbedded": "false"): null,
                "Values": {
                  "Value" @("AttributeID": "STYLENAME", "Changed": "false", "Derived": "false"): "Style-31102953",
                  "Value" @("AttributeID": "CLASSNUMBERSKU", "Changed": "false", "Derived": "false"): "190",
                  "Value" @("AttributeID": "DEPARTMENTSKU", "Changed": "false", "Derived": "false"): "BABY / KIDS TOYS",
                  "Value" @("AttributeID": "PRIMARYVENDORNAME", "Changed": "false", "Derived": "false"): "KIDCO, INC.",
                  "Value" @("AttributeID": "STYLENUMBER", "Changed": "false", "Derived": "false"): "STYLE-31102953",
                  "Value" @("AttributeID": "CLASSSKU", "Changed": "false", "Derived": "false"): "BABY FOOD COOKBOOKS",
                  "Value" @("AttributeID": "SUBDEPARTMENTSKU", "Changed": "false", "Derived": "false"): "BABY BOOKS",
                  "Value" @("AttributeID": "StyleTypeCombination", "Changed": "false", "Derived": "false"): "883|760|190|14844147",
                  "Value" @("AttributeID": "SUBDEPARTMENTNUMBERSKU", "Changed": "false", "Derived": "false"): "760",
                  "Value" @("AttributeID": "DEPARTMENTNUMBERSKU", "Changed": "false", "Derived": "false"): "883",
                  "MultiValue" @("AttributeID": "ASSOCIATEDSKUS", "Changed": "false"): {
                    "Value" @("Changed": "false", "Derived": "false"): "14844147"
                  },
                  "Value" @("AttributeID": "PRIMARYVENDORNUMBER", "Changed": "false", "Derived": "false"): "44078"
                }
              }
            },
            "AssetCrossReference" @("AssetID": "IMG_69617", "Changed": "true", "Type": "Product_WebImage_Reference"): {
              "KeyValue" @("KeyID": "BBBY_IMG_KEY"): "IMG_69617",
              "MetaData": {
                "Value" @("AttributeID": "ACTIVEIMAGE", "Changed": "true", "Derived": "false", "ID": "1"): "Yes",
                "MultiValue" @("AttributeID": "IMAGEREFERENCECREATIONDATE", "Changed": "true"): {
                  "Value" @("Changed": "true", "Derived": "false"): "2013-04-22"
                }
              }
            },
            "Values": {
              "Value" @("AttributeID": "COPYSEQFEATURE15", "Changed": "false", "Derived": "false", "ID": "PRODUCTTYPE"): "Product Type",
              "Value" @("AttributeID": "COPYSEQFEATURE49", "Changed": "false", "Derived": "false", "ID": "MADEIN"): "Made In...",
              "Value" @("AttributeID": "LESSTHANTRUCKLOADLTLITEM", "Changed": "true", "Derived": "false", "ID": "3"): "No",
              "Value" @("AttributeID": "SELLINGUNITHEIGHTCM", "Changed": "true", "Derived": "false"): "0",
              "Value" @("AttributeID": "CUBISCANSTDUNITHEIGHT", "Changed": "false", "Derived": "false"): "0.5",
              "Value" @("AttributeID": "CUBISCANSTDCASELENGTH", "Changed": "false", "Derived": "false"): "9.2",
              "Value" @("AttributeID": "EXCLUSIVITY", "Changed": "true", "Derived": "false", "ID": "2"): "Not exclusive",
              "Value" @("AttributeID": "WAREHOUSEFULFILLMENT", "Changed": "false", "Derived": "false", "ID": "3"): "No",
              "Value" @("AttributeID": "CUBISCANSTDUNITLENGTH", "Changed": "false", "Derived": "false"): "8.5",
              "Value" @("AttributeID": "PATTERNNAME", "Changed": "true", "Derived": "false", "ID": "E9958"): "UNKNOWN",
              "Value" @("AttributeID": "BBBYFORCEBELOWTHELINE", "Changed": "true", "Derived": "false", "ID": "3"): "No",
              "Value" @("AttributeID": "SELLINGUNITDIAMETERIN", "Changed": "true", "Derived": "false"): "0",
              "Value" @("AttributeID": "TBSBLOCKENDINGDATE", "Changed": "true", "Derived": "false"): "2017-01-14 10:14:00",
              "Value" @("AttributeID": "AUTHOR", "Changed": "true", "Derived": "false"): "N/A",
              "Value" @("AttributeID": "CUBISCANINCREMENTALLENGTH", "Changed": "false", "Derived": "false"): "0",
              "Value" @("AttributeID": "NONTEXTILESVENDORINFOONPACKAGE", "Changed": "true", "Derived": "false", "ID": "724"): "N/A",
              "Value" @("AttributeID": "RDSLOGOSTATUS", "Changed": "false", "Derived": "false", "ID": "2"): "Not Required",
              "Value" @("AttributeID": "CUBISCANLASTUPDATEDTIMESTAMP", "Changed": "false", "Derived": "false"): "2021-11-03 00:00:00",
              "Value" @("AttributeID": "PRIMARYUPC", "Changed": "true", "Derived": "false"): "786441610007",
              "Value" @("AttributeID": "BBBYPRICECHANGEREASONCODEANDDESCRIPTION", "Changed": "true", "Derived": "false", "ID": "BC"): "Buyer Clearance",
              "Value" @("AttributeID": "MLBTEAM", "Changed": "true", "Derived": "false", "ID": "1"): "N/A",
              "Value" @("AttributeID": "CUBISCANNONHAZLIBATTERYINDICA", "Changed": "false", "Derived": "false"): "N",
              "Value" @("AttributeID": "NONTEXTILESPACKAGINGTYPE", "Changed": "true", "Derived": "false", "ID": "795"): "N/A",
              "Value" @("AttributeID": "FASTTRACKFLAGPHOTO", "Changed": "true", "Derived": "false", "ID": "3"): "No",
              "Value" @("AttributeID": "CUBISCANSTDUNITWIDTH", "Changed": "false", "Derived": "false"): "6",
              "Value" @("AttributeID": "SELLINGUNITDIAMETERCM", "Changed": "true", "Derived": "false"): "0",
              "Value" @("AttributeID": "SOLDBYCONCEPT", "Changed": "false", "Derived": "false", "ID": "1"): "Bed Bath/Baby",
              "MultiValue" @("AttributeID": "NONTEXEXPLANATIONOFQTYCOUNTONPKGORITEM", "Changed": "true"): {
                "Value" @("Changed": "true", "Derived": "false", "ID": "799"): "N/A"
              },
              "Value" @("AttributeID": "COSTPLUSPLUSPLUSPRICERECEIVED", "Changed": "false", "Derived": "false", "ID": "3"): "No",
              "Value" @("AttributeID": "ASSEMBLYINSTRUCTIONSSTATUS", "Changed": "false", "Derived": "false", "ID": "2"): "Not Required",
              "Value" @("AttributeID": "EMAILCUSTOMERFOROUTOFSTOCK", "Changed": "true", "Derived": "false", "ID": "3"): "No",
              "Value" @("AttributeID": "CUBISCANSTDCASEVOLUME", "Changed": "false", "Derived": "false"): "322.37",
              "Value" @("AttributeID": "BBBYWEBOFFERED", "Changed": "true", "Derived": "false", "ID": "1"): "Yes",
              "Value" @("AttributeID": "SELLINGUNITCUBEIN", "Changed": "true", "Derived": "false"): "0",
              "Value" @("AttributeID": "DESCRIBEFABRICATIONCONTENTINCLUDEIFMULTI", "Changed": "true", "Derived": "false"): "N/A",
              "Value" @("AttributeID": "CUBISCANSTDCASEQUANTITY", "Changed": "false", "Derived": "false"): "12",
              "Value" @("AttributeID": "CUBISCANSTDCASEWIDTH", "Changed": "false", "Derived": "false"): "7.3",
              "Value" @("AttributeID": "CAWEBDISABLED", "Changed": "true", "Derived": "false", "ID": "3"): "No",
              "Value" @("AttributeID": "CUBISCANINCREMENTALWIDTH", "Changed": "false", "Derived": "false"): "0",
              "Value" @("AttributeID": "VENDORDIRECTTOCUSTOMERVDCITEM", "Changed": "true", "Derived": "false", "ID": "3"): "No",
              "Value" @("AttributeID": "PREVENTAUTOFLAGON", "Changed": "false", "Derived": "false", "ID": "3"): "No",
              "Value" @("AttributeID": "CACUSTOMIZATIONFLAG", "Changed": "true", "Derived": "false", "ID": "3"): "No",
              "Value" @("AttributeID": "SELLINGUNITCUBECM", "Changed": "true", "Derived": "false"): "0",
              "Value" @("AttributeID": "CUBISCANSPLINSTRCODE3", "Changed": "false", "Derived": "false"): "N",
              "Value" @("AttributeID": "BABYWEBOFFERED", "Changed": "true", "Derived": "false", "ID": "1"): "Yes",
              "Value" @("AttributeID": "REGIONAL", "Changed": "true", "Derived": "false", "ID": "1"): "N/A",
              "Value" @("AttributeID": "BRANDCODEANDNAME", "Changed": "true", "Derived": "false", "ID": "334"): "Kidco",
              "Value" @("AttributeID": "SELLINGUNITWEIGHTLB", "Changed": "true", "Derived": "false"): "0",
              "Value" @("AttributeID": "PRIMARYVENDORNUMBER", "Changed": "true", "Derived": "false"): "44078",
              "Value" @("AttributeID": "BABYPREORDERMAXCUSTOMERQUANTITY", "Changed": "false", "Derived": "false"): "1",
              "Value" @("AttributeID": "BOOKTHEMES", "Changed": "true", "Derived": "false", "ID": "11"): "N/A",
              "Value" @("AttributeID": "PZREADYFLAG", "Changed": "true", "Derived": "false", "ID": "3"): "No",
              "Value" @("AttributeID": "BBBYWEBAFSFULFILLMENTCODE", "Changed": "false", "Derived": "false"): "N",
              "Value" @("AttributeID": "INNERPACK", "Changed": "true", "Derived": "false"): "12",
              "Value" @("AttributeID": "EMERGENCYITEM", "Changed": "true", "Derived": "false", "ID": "3"): "No",
              "Value" @("AttributeID": "SELLINGUNITWEIGHTKG", "Changed": "true", "Derived": "false"): "0",
              "Value" @("AttributeID": "BOOKFORMAT", "Changed": "true", "Derived": "false", "ID": "8"): "N/A",
              "Value" @("AttributeID": "ISBN", "Changed": "true", "Derived": "false"): "9999999999999",
              "Value" @("AttributeID": "CUBISCANUNITVOLUME", "Changed": "false", "Derived": "false"): "25.5",
              "Value" @("AttributeID": "PRODUCTGUIDECODEANDNAME", "Changed": "true", "Derived": "false", "ID": "125"): "Baby Food Makers",
              "Value" @("AttributeID": "ROLLUPGROUP", "Changed": "true", "Derived": "false"): "1014844147",
              "Value" @("AttributeID": "CUBISCANCAVITYWIDTH", "Changed": "false", "Derived": "false"): "0",
              "Value" @("AttributeID": "CUBISCANSPLINSTRCODE5", "Changed": "false", "Derived": "false"): "N",
              "Value" @("AttributeID": "HAVEVERTICALIMAGE", "Changed": "false", "Derived": "false", "ID": "3"): "No",
              "Value" @("AttributeID": "CAWEBOFFERED", "Changed": "true", "Derived": "false", "ID": "3"): "No",
              "Value" @("AttributeID": "WEBGIFTCARDSKU", "Changed": "true", "Derived": "false", "ID": "3"): "No",
              "Value" @("AttributeID": "SIGNREQUIRED", "Changed": "false", "Derived": "false", "ID": "3"): "No",
              "Value" @("AttributeID": "CUBISCANCAVITYLENGTH", "Changed": "false", "Derived": "false"): "0",
              "Value" @("AttributeID": "SELLINGUNITLENGTHIN", "Changed": "true", "Derived": "false"): "0",
              "Value" @("AttributeID": "FREESHIPSTARTDATE", "Changed": "true", "Derived": "false"): "2014-07-25 00:00:00",
              "Value" @("AttributeID": "SHOWPRODUCTTHUMBNAILS", "Changed": "false", "Derived": "false", "ID": "1"): "Yes",
              "Value" @("AttributeID": "INSTOREONLYSKU", "Changed": "true", "Derived": "false", "ID": "2"): "Web Only",
              "Value" @("AttributeID": "MASTERPRODUCTDESCRIPTION", "Changed": "true", "Derived": "false"): "KidCo Babysteps&trade; Food Preparation Guide",
              "Value" @("AttributeID": "SELLINGUNITLENGTHCM", "Changed": "true", "Derived": "false"): "0",
              "Value" @("AttributeID": "THEME", "Changed": "true", "Derived": "false", "ID": "33"): "N/A",
              "Value" @("AttributeID": "BABYTBSBLOCKED", "Changed": "true", "Derived": "false", "ID": "3"): "No",
              "Value" @("AttributeID": "CAFORCEBELOWTHELINE", "Changed": "true", "Derived": "false", "ID": "3"): "No",
              "Value" @("AttributeID": "ECOMMTAXCODE", "Changed": "false", "Derived": "false"): "P0000000",
              "Value" @("AttributeID": "HAZARDCODE", "Changed": "false", "Derived": "false", "ID": "0"): "Trash",
              "Value" @("AttributeID": "HARMONPREORDERSTATUS", "Changed": "false", "Derived": "false", "ID": "3"): "No",
              "Value" @("AttributeID": "BBBYPREORDERMAXCUSTOMERQUANTITY", "Changed": "false", "Derived": "false"): "1",
              "Value" @("AttributeID": "PRODUCTDESCRIPTION", "Changed": "true", "Derived": "false"): "BABYSTEP FOOD PREP",
              "Value" @("AttributeID": "WARRANTYINFORMATIONSTATUS", "Changed": "false", "Derived": "false", "ID": "2"): "Not Required",
              "Value" @("AttributeID": "SELLINGUNITHEIGHTIN", "Changed": "true", "Derived": "false"): "0",
              "Value" @("AttributeID": "WARRANTY", "Changed": "true", "Derived": "false", "ID": "1"): "N/A",
              "Value" @("AttributeID": "COMMONTERMITEMDESCRIPTION", "Changed": "true", "Derived": "false"): "BABYSTEP FOOD PREP",
              "Value" @("AttributeID": "TBSBLOCKSTARTDATE", "Changed": "true", "Derived": "false"): "2007-08-08 00:00:00",
              "Value" @("AttributeID": "TAXCODE", "Changed": "true", "Derived": "false", "ID": "1"): "GENERAL TAXRATE",
              "Value" @("AttributeID": "ROPISEXCLUSION", "Changed": "true", "Derived": "false", "ID": "1"): "Yes",
              "Value" @("AttributeID": "PLACEHOLDERSKUNUMBER", "Changed": "false", "Derived": "false"): "1200034",
              "Value" @("AttributeID": "CALASTREGULARPRICE", "Changed": "false", "Derived": "false"): "0.00",
              "MultiValue" @("AttributeID": "CMTAGFREEFORM", "Changed": "true"): {
                "Value" @("Changed": "true", "Derived": "false"): "WEB ONLY"
              },
              "Value" @("AttributeID": "USERGUIDESSTATUS", "Changed": "false", "Derived": "false", "ID": "2"): "Not Required",
              "Value" @("AttributeID": "COMPLIESWITHALLAPPLICABLEMEXICANLAWS", "Changed": "true", "Derived": "false", "ID": "1"): "N/A",
              "Value" @("AttributeID": "CAWEBAFSFULFILLMENTCODE", "Changed": "false", "Derived": "false"): "N",
              "Value" @("AttributeID": "FLAMMABLEITEM", "Changed": "true", "Derived": "false", "ID": "3"): "N/A",
              "Value" @("AttributeID": "LANDEDCOST", "Changed": "true", "Derived": "false"): "4.75",
              "Value" @("AttributeID": "VIDEOSTATUS", "Changed": "false", "Derived": "false", "ID": "2"): "Not Required",
              "Value" @("AttributeID": "AVAILABLEFORSALEINUS", "Changed": "true", "Derived": "false", "ID": "Y"): "Can be Sold In",
              "Value" @("AttributeID": "AVAILABLEFORSALEINMX", "Changed": "true", "Derived": "false", "ID": "P"): "Pending (Cannot be Sold In)",
              "Value" @("AttributeID": "PLMSTYLENUMBER", "Changed": "false", "Derived": "false"): "S00048778",
              "Value" @("AttributeID": "HARMONWEBOFFERED", "Changed": "false", "Derived": "false", "ID": "3"): "No",
              "Value" @("AttributeID": "SIZE", "Changed": "true", "Derived": "false", "ID": "9926"): "BOOK",
              "Value" @("AttributeID": "ITEMSOURCESYSTEM", "Changed": "false", "Derived": "false", "ID": "1"): "PLM",
              "Value" @("AttributeID": "JDADESCRIPTION", "Changed": "true", "Derived": "false"): "BABYSTEP FOOD PREP",
              "Value" @("AttributeID": "PLMMARKETINGNAME", "Changed": "false", "Derived": "false"): "JACQUARD BEACH TOWEL - Sunshine and Summer",
              "MultiValue" @("AttributeID": "SHORTCUSTOMSDESCRIPTION", "Changed": "true"): {
                "Value" @("Changed": "true", "Derived": "false"): "BABYSTEP FOOD PREP"
              },
              "Value" @("AttributeID": "BRANDCATEGORY", "Changed": "true", "Derived": "false", "ID": "3"): "National Brand",
              "Value" @("AttributeID": "BABYWEBAFSQTY", "Changed": "false", "Derived": "false"): "0",
              "Value" @("AttributeID": "AVAILABLEFORSALEINCANADA", "Changed": "true", "Derived": "false", "ID": "Y"): "Can be Sold In",
              "Value" @("AttributeID": "APPROVEDFROMWORKFLOW", "Changed": "true", "Derived": "false"): "Item Update",
              "Value" @("AttributeID": "SELLINGUNITWIDTHIN", "Changed": "true", "Derived": "false"): "0",
              "Value" @("AttributeID": "PLMSKUNUMBER", "Changed": "false", "Derived": "false"): "C0/JF23-3058345-35|SKU",
              "Value" @("AttributeID": "CAPRICECHANGEREASONCODEANDDESCRIPTION", "Changed": "true", "Derived": "false", "ID": "BC"): "Buyer Clearance",
              "Value" @("AttributeID": "AVAILABLEFORDISTRIBUTIONINUS", "Changed": "true", "Derived": "false", "ID": "1"): "Yes",
              "Value" @("AttributeID": "EVENTNAME", "Changed": "true", "Derived": "false"): "BBB KIDCO SAFETY PLUS",
              "Value" @("AttributeID": "CUSTOMIZATIONAVAILABILITY", "Changed": "true", "Derived": "false", "ID": "N"): "Customization not available",
              "Value" @("AttributeID": "SETCODE", "Changed": "true", "Derived": "false", "ID": "0"): "Not a Set",
              "Value" @("AttributeID": "MLSTEAM", "Changed": "true", "Derived": "false", "ID": "10"): "N/A",
              "Value" @("AttributeID": "CAWEBCOST", "Changed": "false", "Derived": "false"): "4.750",
              "Value" @("AttributeID": "SELLINGUNITWIDTHCM", "Changed": "true", "Derived": "false"): "0",
              "Value" @("AttributeID": "LENGTHHEIGHTOFRAILS", "Changed": "true", "Derived": "false"): "N/A",
              "Value" @("AttributeID": "VDCSHIPPINGCUTOFFOFFSET", "Changed": "true", "Derived": "false"): "0",
              "Value" @("AttributeID": "LIGHTINGFACTSSTATUS", "Changed": "false", "Derived": "false", "ID": "2"): "Not Required",
              "Value" @("AttributeID": "PRODUCTPROFILE", "Changed": "true", "Derived": "false", "ID": "1"): "N/A",
              "Value" @("AttributeID": "L4BBBYBABYCATEGORY", "Changed": "true", "Derived": "false", "ID": "78"): "Processors, Blenders, & Juicers",
              "Value" @("AttributeID": "ASSEMBLEDPRODUCTCUBEIN", "Changed": "true", "Derived": "false"): "0",
              "Value" @("AttributeID": "BBBYTBSBLOCKED", "Changed": "true", "Derived": "false", "ID": "3"): "No",
              "Value" @("AttributeID": "WARRANTYFLAG", "Changed": "true", "Derived": "false", "ID": "3"): "No",
              "Value" @("AttributeID": "PRODUCTTYPE", "Changed": "true", "Derived": "false", "ID": "76"): "Book",
              "Value" @("AttributeID": "TICKETTYPEREG", "Changed": "true", "Derived": "false", "ID": "0"): "NO TICKETS SPECIFIED",
              "Value" @("AttributeID": "STDASSEMBLEDPRODUCTWEIGHT", "Changed": "true", "Derived": "false"): "0",
              "Value" @("AttributeID": "PARTSLISTSTATUS", "Changed": "false", "Derived": "false", "ID": "2"): "Not Required",
              "Value" @("AttributeID": "FREIGHTCLASS", "Changed": "true", "Derived": "false", "ID": "1"): "Do Not Use-0",
              "Value" @("AttributeID": "CHAINPRICECHANGEREASONCODEANDDESCRIPTION", "Changed": "true", "Derived": "false", "ID": "BC"): "Buyer Clearance",
              "Value" @("AttributeID": "ASSEMBLEDPRODUCTCUBECM", "Changed": "true", "Derived": "false"): "0",
              "Value" @("AttributeID": "MADEIN", "Changed": "true", "Derived": "false", "ID": "1"): "N/A",
              "Value" @("AttributeID": "PRETICKETED", "Changed": "true", "Derived": "false", "ID": "3"): "N/A",
              "Value" @("AttributeID": "STYLENAME", "Changed": "true", "Derived": "false"): "Style-31102953",
              "Value" @("AttributeID": "BBBYLASTREGULARPRICE", "Changed": "false", "Derived": "false"): "0.00",
              "Value" @("AttributeID": "CAWEBSTATUS", "Changed": "true", "Derived": "false"): "D",
              "MultiValue" @("AttributeID": "LIFESTYLE", "Changed": "true"): {
                "Value" @("Changed": "true", "Derived": "false", "ID": "1"): "N/A"
              },
              "Value" @("AttributeID": "LONGPRODUCTDESCRIPTION", "Changed": "true", "Derived": "false"): "BABYSTEP FOOD PREP",
              "Value" @("AttributeID": "DIMENSIONSORUNITOFMEASUREONPACKAGEORITEM", "Changed": "true", "Derived": "false", "ID": "886"): "N/A",
              "Value" @("AttributeID": "DEPARTMENTSKU", "Changed": "false", "Derived": "false"): "BABY / KIDS TOYS",
              "Value" @("AttributeID": "COLORGROUPCODEANDNAME", "Changed": "true", "Derived": "false", "ID": "17"): "Multi",
              "Value" @("AttributeID": "STYLENUMBER", "Changed": "true", "Derived": "false"): "STYLE-31102953",
              "Value" @("AttributeID": "CLASSSKU", "Changed": "false", "Derived": "false"): "BABY FOOD COOKBOOKS",
              "Value" @("AttributeID": "BABYFORCEBELOWTHELINE", "Changed": "true", "Derived": "false", "ID": "3"): "No",
              "Value" @("AttributeID": "SUBDEPARTMENTSKU", "Changed": "false", "Derived": "false"): "BABY BOOKS",
              "Value" @("AttributeID": "CACLEARANCE", "Changed": "true", "Derived": "false", "ID": "1"): "Yes",
              "Value" @("AttributeID": "AGEREQUIREMENTSAPPROPRIATENESS", "Changed": "true", "Derived": "false"): "N/A",
              "Value" @("AttributeID": "SUBDEPARTMENTNUMBERSKU", "Changed": "false", "Derived": "false"): "760",
              "Value" @("AttributeID": "SKU", "Changed": "false", "Derived": "false"): "14844147",
              "Value" @("AttributeID": "BBBYWEBAFSQTY", "Changed": "false", "Derived": "false"): "0",
              "Value" @("AttributeID": "AWARDSPARENTTRAININGBOOKSTICKERBOOK", "Changed": "true", "Derived": "false", "ID": "6"): "N/A",
              "Value" @("AttributeID": "HARMONCLEARANCE", "Changed": "false", "Derived": "false", "ID": "3"): "No",
              "Value" @("AttributeID": "BBBYWEBCOST", "Changed": "false", "Derived": "false"): "4.750",
              "Value" @("AttributeID": "HARMONFORCEBELOWTHELINE", "Changed": "false", "Derived": "false", "ID": "3"): "No",
              "Value" @("AttributeID": "BBBYPREORDERSTATUS", "Changed": "false", "Derived": "false", "ID": "3"): "No",
              "Value" @("AttributeID": "ASSEMBLEDPRODUCTLENGTHCM", "Changed": "true", "Derived": "false"): "0",
              "Value" @("AttributeID": "SEASON", "Changed": "true", "Derived": "false", "ID": "BAS"): "Basic",
              "Value" @("AttributeID": "CAPREORDERSTATUS", "Changed": "false", "Derived": "false", "ID": "3"): "No",
              "Value" @("AttributeID": "CASECUBECM", "Changed": "true", "Derived": "false"): "0",
              "Value" @("AttributeID": "NUMBEROFPAGES", "Changed": "true", "Derived": "false"): "N/A",
              "Value" @("AttributeID": "HARMONWEBSTATUS", "Changed": "false", "Derived": "false"): "I",
              "Value" @("AttributeID": "BABYWEBOFFEREDDATE", "Changed": "true", "Derived": "false"): "2007-09-16 00:00:00",
              "Value" @("AttributeID": "FREESHIPSTARTDATENEW", "Changed": "true", "Derived": "false"): "2014-07-25",
              "Value" @("AttributeID": "HAVE478X478IMAGE", "Changed": "true", "Derived": "false", "ID": "3"): "No",
              "Value" @("AttributeID": "SENDSKUTOHARMON", "Changed": "false", "Derived": "false", "ID": "3"): "No",
              "Value" @("AttributeID": "COMPLIANCEINDICATOR", "Changed": "false", "Derived": "false", "ID": "N"): "No Compliance review, no feed to Compliance",
              "Value" @("AttributeID": "ASSEMBLEDPRODUCTHEIGHTIN", "Changed": "true", "Derived": "false"): "0",
              "Value" @("AttributeID": "BABYCLEARANCE", "Changed": "true", "Derived": "false", "ID": "1"): "Yes",
              "Value" @("AttributeID": "USECOMMFULFILLMENTRULE", "Changed": "true", "Derived": "false", "ID": "E"): "Standard ECOM Processing",
              "Value" @("AttributeID": "ASSEMBLEDPRODUCTHEIGHTCM", "Changed": "true", "Derived": "false"): "0",
              "Value" @("AttributeID": "COMPLIESWITHALLAPPLICABLECANADIANPROVINC", "Changed": "true", "Derived": "false", "ID": "1"): "N/A",
              "Value" @("AttributeID": "SENDSKUTOBEYOND", "Changed": "false", "Derived": "false", "ID": "3"): "No",
              "Value" @("AttributeID": "TRANSFERRABLETOMEXICO", "Changed": "true", "Derived": "false", "ID": "3"): "No",
              "Value" @("AttributeID": "HAVEHIGHRESOLUTIONIMAGE", "Changed": "true", "Derived": "false", "ID": "1"): "Yes",
              "Value" @("AttributeID": "CAWEBAFSQTY", "Changed": "false", "Derived": "false"): "0",
              "Value" @("AttributeID": "MEXICOECOMMFULFILLMENTRULE", "Changed": "true", "Derived": "false", "ID": "P"): "Pending Action",
              "Value" @("AttributeID": "BABYPRICECHANGEREASONCODEANDDESCRIPTION", "Changed": "true", "Derived": "false", "ID": "BC"): "Buyer Clearance",
              "Value" @("AttributeID": "BBBYCLEARANCE", "Changed": "true", "Derived": "false", "ID": "1"): "Yes",
              "Value" @("AttributeID": "TRANSFERRABLETOCANADA", "Changed": "true", "Derived": "false", "ID": "1"): "Yes",
              "Value" @("AttributeID": "ASSEMBLEDPRODUCTDIAMETERIN", "Changed": "true", "Derived": "false"): "0",
              "Value" @("AttributeID": "FITSOPENINGS", "Changed": "true", "Derived": "false"): "N/A",
              "Value" @("AttributeID": "BABYWEBDISABLED", "Changed": "true", "Derived": "false", "ID": "1"): "Yes",
              "Value" @("AttributeID": "PRODUCTUSAGE", "Changed": "true", "Derived": "false"): "BABYSTEP FOOD PREP",
              "Value" @("AttributeID": "SIZETEXT", "Changed": "true", "Derived": "false"): "BOOK",
              "Value" @("AttributeID": "ROLLUPTYPECODEANDNAME", "Changed": "true", "Derived": "false", "ID": "00"): "None",
              "Value" @("AttributeID": "ASSEMBLEDPRODUCTDIAMETERCM", "Changed": "true", "Derived": "false"): "0",
              "Value" @("AttributeID": "SHARKTANK", "Changed": "true", "Derived": "false", "ID": "2"): "N/A",
              "Value" @("AttributeID": "BBBYWEBREGULARPRICE", "Changed": "false", "Derived": "false"): "4.99",
              "Value" @("AttributeID": "CONTRACTUALRIGHTSTODISTRIBUTEINCANADASOB", "Changed": "true", "Derived": "false", "ID": "1"): "N/A",
              "Value" @("AttributeID": "BUYUNITS", "Changed": "true", "Derived": "false", "ID": "EA"): "EACHES",
              "Value" @("AttributeID": "PARTORMODELNUMBER", "Changed": "true", "Derived": "false"): "F100",
              "Value" @("AttributeID": "DEPARTMENTNUMBERSKU", "Changed": "false", "Derived": "false"): "883",
              "Value" @("AttributeID": "NFLTEAM", "Changed": "true", "Derived": "false", "ID": "32"): "N/A",
              "Value" @("AttributeID": "CASELENGTHIN", "Changed": "true", "Derived": "false"): "0",
              "Value" @("AttributeID": "UNITCOST", "Changed": "true", "Derived": "false"): "4.75",
              "Value" @("AttributeID": "VENDORIMPORTDOMESTICFLAG", "Changed": "true", "Derived": "false"): "D",
              "MultiValue" @("AttributeID": "ADDITIONALUPC", "Changed": "true"): {
                "Value" @("Changed": "true", "Derived": "false"): "86441610008"
              },
              "Value" @("AttributeID": "SWATCH", "Changed": "false", "Derived": "false", "ID": "3"): "No",
              "Value" @("AttributeID": "CASELENGTHCM", "Changed": "true", "Derived": "false"): "0",
              "Value" @("AttributeID": "CAWEBREGULARPRICE", "Changed": "false", "Derived": "false"): "5.99",
              "Value" @("AttributeID": "BABYWEBCOST", "Changed": "false", "Derived": "false"): "4.750",
              "Value" @("AttributeID": "BABYENABLESITEDATE", "Changed": "true", "Derived": "false"): "2007-10-16 00:00:00",
              "Value" @("AttributeID": "BBBYENABLESITEDATE", "Changed": "true", "Derived": "false"): "2007-10-16 00:00:00",
              "Value" @("AttributeID": "MULTIVENDORINDICATOR", "Changed": "true", "Derived": "false", "ID": "1"): "1",
              "Value" @("AttributeID": "ASSEENONTV", "Changed": "true", "Derived": "false", "ID": "2"): "N/A",
              "Value" @("AttributeID": "PUBLISHER", "Changed": "true", "Derived": "false"): "N/A",
              "Value" @("AttributeID": "ASSEMBLEDPRODUCTWEIGHTLB", "Changed": "true", "Derived": "false"): "0",
              "Value" @("AttributeID": "BABYWEBAFSFULFILLMENTCODE", "Changed": "false", "Derived": "false"): "S",
              "Value" @("AttributeID": "BBBYWEBPRICESTRING", "Changed": "true", "Derived": "false", "ID": "2"): "\$%L",
              "Value" @("AttributeID": "CASEHEIGHTIN", "Changed": "true", "Derived": "false"): "0",
              "Value" @("AttributeID": "CHAINREGULARPRICE", "Changed": "true", "Derived": "false"): "4.99",
              "Value" @("AttributeID": "HARMONWEBDISABLED", "Changed": "false", "Derived": "false", "ID": "3"): "No",
              "Value" @("AttributeID": "NBATEAM", "Changed": "true", "Derived": "false", "ID": "33"): "N/A",
              "Value" @("AttributeID": "GENRE", "Changed": "true", "Derived": "false", "ID": "3"): "N/A",
              "Value" @("AttributeID": "CASEHEIGHTCM", "Changed": "true", "Derived": "false"): "0",
              "Value" @("AttributeID": "BABYPREORDERSTATUS", "Changed": "false", "Derived": "false", "ID": "3"): "No",
              "Value" @("AttributeID": "ASSEMBLEDPRODUCTWEIGHTKG", "Changed": "true", "Derived": "false"): "0",
              "Value" @("AttributeID": "PRIORITYFLAG", "Changed": "false", "Derived": "false", "ID": "3"): "3-Low",
              "Value" @("AttributeID": "ASSEMBLEDPRODUCTLENGTHIN", "Changed": "true", "Derived": "false"): "0",
              "Value" @("AttributeID": "OWNEDBYCONCEPT", "Changed": "true", "Derived": "false", "ID": "1"): "Baby",
              "Value" @("AttributeID": "CLASSNUMBERSKU", "Changed": "false", "Derived": "false"): "190",
              "Value" @("AttributeID": "CASECUBEIN", "Changed": "true", "Derived": "false"): "0",
              "Value" @("AttributeID": "ALLOWBATCHSIGN", "Changed": "false", "Derived": "false", "ID": "3"): "No",
              "Value" @("AttributeID": "CASEWEIGHTKG", "Changed": "true", "Derived": "false"): "0",
              "Value" @("AttributeID": "BBBYWEBSTATUS", "Changed": "true", "Derived": "false"): "D",
              "Value" @("AttributeID": "POSCASHREGISTERDESCRIPTION", "Changed": "true", "Derived": "false"): "BABYSTEP FOOD PREP",
              "Value" @("AttributeID": "BBBYWEBOFFEREDDATE", "Changed": "true", "Derived": "false"): "2007-09-16 00:00:00",
              "Value" @("AttributeID": "BABYCUSTOMIZATIONFLAG", "Changed": "true", "Derived": "false", "ID": "3"): "No",
              "Value" @("AttributeID": "ASSEMBLEDPRODUCTWIDTHCM", "Changed": "true", "Derived": "false"): "0",
              "Value" @("AttributeID": "BUYERNAME", "Changed": "true", "Derived": "false", "ID": "994"): "LILLY DURYEE",
              "Value" @("AttributeID": "INITIALSHIPDATE", "Changed": "true", "Derived": "false"): "2016-03-17",
              "Value" @("AttributeID": "BABYLASTREGULARPRICE", "Changed": "false", "Derived": "false"): "0.00",
              "Value" @("AttributeID": "BABYONLY", "Changed": "true", "Derived": "false", "ID": "1"): "Yes",
              "Value" @("AttributeID": "CPSIADISTINGUISHINGPERMANENTMARKSCOMPLIA", "Changed": "true", "Derived": "false", "ID": "3"): "N/A",
              "Value" @("AttributeID": "PLANNING", "Changed": "true", "Derived": "false", "ID": "1"): "Yes",
              "Value" @("AttributeID": "INITIALRETAIL", "Changed": "true", "Derived": "false"): "9.99",
              "Value" @("AttributeID": "CREATEDATE", "Changed": "true", "Derived": "false"): "2016-03-18 00:00:00",
              "MultiValue" @("AttributeID": "ASSOCIATEDWEBPRODUCTID", "Changed": "true"): {
                "Value" @("Changed": "true", "Derived": "false"): "1014844147"
              },
              "Value" @("AttributeID": "CHAINCOST", "Changed": "false", "Derived": "false"): "4.750",
              "Value" @("AttributeID": "CAFREESHIP", "Changed": "true", "Derived": "false", "ID": "1"): "Yes",
              "Value" @("AttributeID": "BUYCODE", "Changed": "true", "Derived": "false", "ID": "S"): "Store Order",
              "Value" @("AttributeID": "BABYWEBSTATUS", "Changed": "true", "Derived": "false"): "D",
              "Value" @("AttributeID": "CAPREORDERMAXCUSTOMERQUANTITY", "Changed": "false", "Derived": "false"): "1",
              "Value" @("AttributeID": "HARMONPREORDERMAXCUSTOMERQUANTITY", "Changed": "false", "Derived": "false"): "1",
              "Value" @("AttributeID": "BBBYWEBDISABLED", "Changed": "true", "Derived": "false", "ID": "1"): "Yes",
              "Value" @("AttributeID": "COPYSEQFEATURE41", "Changed": "false", "Derived": "false", "ID": "UNIQUEFEATURES"): "Unique Features",
              "Value" @("AttributeID": "PDMITEMTYPE", "Changed": "true", "Derived": "false", "ID": "5"): "Standard",
              "Value" @("AttributeID": "BABYWEBREGULARPRICE", "Changed": "false", "Derived": "false"): "4.99",
              "Value" @("AttributeID": "FREESHIPENDDATE", "Changed": "true", "Derived": "false"): "2014-09-03 00:00:00",
              "Value" @("AttributeID": "CANADAECOMMFULFILLMENTRULE", "Changed": "true", "Derived": "false", "ID": "E"): "Standard ECOM Processing",
              "Value" @("AttributeID": "BABYFREESHIP", "Changed": "true", "Derived": "false", "ID": "1"): "Yes",
              "Value" @("AttributeID": "NUMBEROFBOXESPERITEM", "Changed": "true", "Derived": "false"): "1",
              "Value" @("AttributeID": "ITEMTYPEDESCRIPTION", "Changed": "true", "Derived": "false", "ID": "01"): "Standard Item",
              "Value" @("AttributeID": "BRANDNAME", "Changed": "true", "Derived": "false"): "Kidco",
              "Value" @("AttributeID": "BBBYCUSTOMIZATIONFLAG", "Changed": "true", "Derived": "false", "ID": "3"): "No",
              "Value" @("AttributeID": "CONTRACTUALRIGHTSTODISTRIBUTEINMEXICOSOB", "Changed": "true", "Derived": "false", "ID": "1"): "N/A",
              "Value" @("AttributeID": "UNITPRICINGREQUIRED", "Changed": "true", "Derived": "false", "ID": "3"): "No",
              "Value" @("AttributeID": "ASSORTEDSKU", "Changed": "true", "Derived": "false", "ID": "3"): "No",
              "Value" @("AttributeID": "CASEPACK", "Changed": "true", "Derived": "false"): "12",
              "Value" @("AttributeID": "BABYWEBPRICESTRING", "Changed": "true", "Derived": "false", "ID": "2"): "\$%L",
              "Value" @("AttributeID": "COPYSEQFEATURE42", "Changed": "false", "Derived": "false", "ID": "THEME"): "Theme",
              "Value" @("AttributeID": "BULLETEDWEBCOPY", "Changed": "true", "Derived": "false"): "<lt/>ul<gt/><lt/>li<gt/>ISBN 13: 9999999999999<lt/>/li<gt/>\n<lt/>/ul<gt/>",
              "Value" @("AttributeID": "NHLTEAM", "Changed": "true", "Derived": "false", "ID": "13"): "N/A",
              "Value" @("AttributeID": "COPYSEQFEATURE43", "Changed": "false", "Derived": "false", "ID": "AUTHOR"): "Author",
              "Value" @("AttributeID": "UNITFREIGHTCLASS", "Changed": "true", "Derived": "false"): "Do Not Use-0",
              "Value" @("AttributeID": "PROPOSITION65WARNINGAPPLIES", "Changed": "true", "Derived": "false", "ID": "4"): "Yes, item is compliant - warning not required",
              "Value" @("AttributeID": "COLLEGE", "Changed": "true", "Derived": "false", "ID": "62"): "N/A",
              "Value" @("AttributeID": "CUBISCANSTABILIZATIONCODE", "Changed": "false", "Derived": "false"): "HIGH",
              "Value" @("AttributeID": "CUBISCANUNITWEIGHT", "Changed": "false", "Derived": "false"): "0.45",
              "Value" @("AttributeID": "COLOR", "Changed": "true", "Derived": "false", "ID": "963"): "MULTI",
              "Value" @("AttributeID": "CUBISCANSPLINSTRCODE10", "Changed": "false", "Derived": "false"): "N",
              "Value" @("AttributeID": "MEXICOSUBSCRIPTIONELIGIBILITY", "Changed": "false", "Derived": "false", "ID": "3"): "No",
              "Value" @("AttributeID": "CUBISCANSPLINSTRCODE8", "Changed": "false", "Derived": "false"): "N",
              "Value" @("AttributeID": "CUBISCANSTDCASEHEIGHT", "Changed": "false", "Derived": "false"): "4.8",
              "Value" @("AttributeID": "COPYSEQFEATURE44", "Changed": "false", "Derived": "false", "ID": "NUMBEROFPAGES"): "Number of Pages",
              "Value" @("AttributeID": "NUTRITIONLABELSTATUS", "Changed": "false", "Derived": "false", "ID": "2"): "Not Required",
              "Value" @("AttributeID": "CHAINLASTREGULARPRICE", "Changed": "false", "Derived": "false"): "9.99",
              "Value" @("AttributeID": "CHAINSTATUS", "Changed": "true", "Derived": "false", "ID": "P"): "TO BE PURGED",
              "Value" @("AttributeID": "COPYSEQFEATURE11", "Changed": "false", "Derived": "false", "ID": "COLOR"): "Color",
              "Value" @("AttributeID": "ENERGYGUIDESTATUS", "Changed": "false", "Derived": "false", "ID": "2"): "Not Required",
              "Value" @("AttributeID": "COPYSEQFEATURE45", "Changed": "false", "Derived": "false", "ID": "PUBLISHER"): "Publisher",
              "Value" @("AttributeID": "FREESHIPENDDATENEW", "Changed": "true", "Derived": "false"): "2014-09-03",
              "Value" @("AttributeID": "MASTER255SHORTDESCRIPTION", "Changed": "true", "Derived": "false"): "Begin a healthy, nutritious, natural diet for your baby that will last a lifetime. This handbook will walk you through the entire BabySteps system, providing direction in the preparation, storage and feeding of the most beneficial food for your baby.",
              "Value" @("AttributeID": "CUBISCANINCREMENTALHEIGHT", "Changed": "false", "Derived": "false"): "0",
              "Value" @("AttributeID": "SELLUNITS", "Changed": "true", "Derived": "false", "ID": "EA"): "EACHES",
              "Value" @("AttributeID": "BACKORDERSTATUS", "Changed": "false", "Derived": "false", "ID": "3"): "No",
              "Value" @("AttributeID": "CANADASUBSCRIPTIONELIGIBILITY", "Changed": "false", "Derived": "false", "ID": "3"): "No",
              "Value" @("AttributeID": "CASEWIDTHIN", "Changed": "true", "Derived": "false"): "0",
              "Value" @("AttributeID": "MASTERBULLETEDCOPY", "Changed": "true", "Derived": "false"): "<lt/>ul<gt/><lt/>li<gt/>In this guide you will find: Helpful hints for fresh food selection; cooking methods; age appropriate foods and serving sizes; sample recipes.<lt/>/li<gt/><lt/>li<gt/>92 pages.<lt/>/li<gt/><lt/>/ul<gt/>",
              "Value" @("AttributeID": "CUBISCANSPLINSTRCDENVELOPEFLG", "Changed": "false", "Derived": "false"): "N",
              "Value" @("AttributeID": "COPYSEQFEATURE12", "Changed": "false", "Derived": "false", "ID": "ASSEMBLEDPRODUCTLENGTHIN"): "Product Depth (in)",
              "Value" @("AttributeID": "COPYSEQFEATURE46", "Changed": "false", "Derived": "false", "ID": "PUBLISHDATE"): "Publish Date",
              "Value" @("AttributeID": "CATBSBLOCKED", "Changed": "true", "Derived": "false", "ID": "3"): "No",
              "Value" @("AttributeID": "CUBISCANSHIPALONE", "Changed": "false", "Derived": "false"): "N",
              "Value" @("AttributeID": "CUBISCANCONVEYABLE", "Changed": "false", "Derived": "false"): "Y",
              "Value" @("AttributeID": "BUYINGCONTACTEMAIL", "Changed": "true", "Derived": "false"): "LILLY.DURYEE@BEDBATH.COM",
              "Value" @("AttributeID": "COPYSEQFEATURE13", "Changed": "false", "Derived": "false", "ID": "ASSEMBLEDPRODUCTWIDTHIN"): "Product Width (in)",
              "Value" @("AttributeID": "CASEWIDTHCM", "Changed": "true", "Derived": "false"): "0",
              "Value" @("AttributeID": "COPYSEQFEATURE47", "Changed": "false", "Derived": "false", "ID": "ISBN"): "ISBN 13",
              "Value" @("AttributeID": "CUBISCANSPLINSTRCDSWOP", "Changed": "false", "Derived": "false"): "N",
              "Value" @("AttributeID": "MINIMUMREPLENISHMENTQUANTITY", "Changed": "true", "Derived": "false"): "1",
              "Value" @("AttributeID": "MERCHANDISESECTION", "Changed": "false", "Derived": "false", "ID": "0030"): "MISC",
              "Value" @("AttributeID": "PROP65STATUS", "Changed": "false", "Derived": "false", "ID": "2"): "Not Required",
              "Value" @("AttributeID": "CUBISCANSPLINSTRCODE2", "Changed": "false", "Derived": "false"): "N",
              "Value" @("AttributeID": "PRIMARYVENDORNAME", "Changed": "false", "Derived": "false"): "KIDCO, INC.",
              "Value" @("AttributeID": "USSUBSCRIPTIONELIGIBILITY", "Changed": "false", "Derived": "false", "ID": "3"): "No",
              "Value" @("AttributeID": "BUYINGCONTACT", "Changed": "true", "Derived": "false"): "LILLY DURYEE",
              "Value" @("AttributeID": "CASEWEIGHTLB", "Changed": "true", "Derived": "false"): "0",
              "Value" @("AttributeID": "CUBISCANCAVITYHEIGHT", "Changed": "false", "Derived": "false"): "0",
              "Value" @("AttributeID": "VENDORWEBPRODUCT", "Changed": "true", "Derived": "false"): "Kidco Babystep Food Prep Multi Book ",
              "Value" @("AttributeID": "PRODUCTDIMENSIONSSTATUS", "Changed": "false", "Derived": "false", "ID": "2"): "Not Required",
              "Value" @("AttributeID": "SECURITYTAG", "Changed": "true", "Derived": "false", "ID": "3"): "No",
              "Value" @("AttributeID": "CUBISCANSTDCASEWEIGHT", "Changed": "false", "Derived": "false"): "5.2",
              "Value" @("AttributeID": "MINIMUMORDERQUANTITY", "Changed": "true", "Derived": "false"): "1",
              "Value" @("AttributeID": "COPYSEQFEATURE14", "Changed": "false", "Derived": "false", "ID": "ASSEMBLEDPRODUCTDIAMETERIN"): "Product Diameter (in) - calc",
              "Value" @("AttributeID": "ASSEMBLEDPRODUCTWIDTHIN", "Changed": "true", "Derived": "false"): "0",
              "Value" @("AttributeID": "BBBYFREESHIP", "Changed": "true", "Derived": "false", "ID": "1"): "Yes",
              "Value" @("AttributeID": "COPYSEQFEATURE48", "Changed": "false", "Derived": "false", "ID": "WARRANTY"): "Warranty",
              "Value" @("AttributeID": "CUBISCANSPLINSTRCODE4", "Changed": "false", "Derived": "false"): "N",
              "Value" @("AttributeID": "EPHPATH", "Changed": "false", "Derived": "true"): "Primary Product Hierarchy||Enterprise Product Hierarchy||Books||14844147_BABYSTEP FOOD PREP#EPH_451367"
            }
          }
        }
      }
    }
  }
}