#%RAML 1.0
title: sample
/sample:
  get:
   responses:
     200:
       body:
        application/json:
          example:
            {
              "Message":"sucess"
            }
            
    

    